Feature/UI (#11)
* first UI iteration

* rework and tests

* cleanup

* readme updated

* cleanup

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -17,6 +17,13 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 printf "\e[33;1m%s\e[0m\n" 'Finished running bloc tests'
+printf "\e[33;1m%s\e[0m\n" 'Running unit tests'
+flutter test test/unit_test.dart
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" 'unit tests error'
+  exit 1
+fi
+printf "\e[33;1m%s\e[0m\n" 'Finished running unit tests'
 printf "\e[33;1m%s\e[0m\n" 'Running golden tests'
 flutter test test/golden_test.dart --tags=golden
 if [ $? -ne 0 ]; then
