fixed arrow without end element

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -3,6 +3,13 @@ if [[ `git status --porcelain` ]]; then
   printf "\e[31;1m%s\e[0m\n" 'This script needs to run against committed code only. Please commit or stash you changes.'
   exit 1
 fi
+printf "\e[33;1m%s\e[0m\n" 'Running test coverage'
+flutter test --coverage
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" 'test coverage error'
+  exit 1
+fi
+printf "\e[33;1m%s\e[0m\n" 'Finished running test coverage'
 printf "\e[33;1m%s\e[0m\n" 'Running bloc tests'
 flutter test test/bloc_test.dart
 if [ $? -ne 0 ]; then
